
objs-y += kmain.o
objs-y += string.o
objs-y += debug.o
objs-y += basic_printf.o
objs-y += sprintf.o
objs-y += char_buf.o
objs-y += dump_mem.o
objs-y += strtol.o
objs-y += scheduler.o
objs-y += strerror.o

