
objs-y += debug.o
objs-y += char_buf.o
objs-y += dump_mem.o
objs-y += crc.o
objs-y += time.o
objs-y += ktimer.o
objs-y += sys_user.o
objs-y += uname.o
objs-$(CONFIG_KERNEL_TESTS) += ktest.o
objs-y += cmdline.o

subdir-y += str
subdir-y += sched

