
objs-y += login.o

common-objs-y += arg_parser.o
common-objs-y += file.o
common-objs-y += db.o
common-objs-y += db_passwd.o
common-objs-y += db_group.o
common-objs-y += strdupx.o
common-objs-y += login_common.o

