#ifndef INCLUDE_UAPI_PROTURA_EVENT_KEYBOARD_H
#define INCLUDE_UAPI_PROTURA_EVENT_KEYBOARD_H

/* This is recorded in the 'value' field of the event */
enum {
    KERN_EVENT_KEY_PRESS,
    KERN_EVENT_KEY_RELEASE,
};

/* All of the valid Keysyms a keyboard can send. In the kernel these are
 * indexes into the keymaps, but for the event interface they are sent directly
 * to userspace. */
enum {
    KS_NULL,
    KS_ESC,
    KS_ONE,
    KS_TWO,
    KS_THREE,
    KS_FOUR,
    KS_FIVE,
    KS_SIX,
    KS_SEVEN,
    KS_EIGHT,
    KS_NINE,
    KS_ZERO,
    KS_MINUS,
    KS_EQUALS,
    KS_BACKSPACE,
    KS_TAB,
    KS_Q,
    KS_W,
    KS_E,
    KS_R,
    KS_T,
    KS_Y,
    KS_U,
    KS_I,
    KS_O,
    KS_P,
    KS_LEFT_BRACE,
    KS_RIGHT_BRACE,
    KS_ENTER,
    KS_LCTRL,
    KS_A,
    KS_S,
    KS_D,
    KS_F,
    KS_G,
    KS_H,
    KS_J,
    KS_K,
    KS_L,
    KS_SEMICOLON,
    KS_SINGLE_QUOTE,
    KS_BACKTICK,
    KS_LSHIFT,
    KS_BACKSLASH,
    KS_Z,
    KS_X,
    KS_C,
    KS_V,
    KS_B,
    KS_N,
    KS_M,
    KS_COMMA,
    KS_PERIOD,
    KS_SLASH,
    KS_RSHIFT,
    KS_KP_MULTIPLY,
    KS_ALT,
    KS_SPACE,
    KS_CAPS_LOCK,
    KS_F1,
    KS_F2,
    KS_F3,
    KS_F4,
    KS_F5,
    KS_F6,
    KS_F7,
    KS_F8,
    KS_F9,
    KS_F10,
    KS_NUM_LOCK,
    KS_SCROLL_LOCK,
    KS_KP_SEVEN,
    KS_KP_EIGHT,
    KS_KP_NINE,
    KS_KP_MINUS,
    KS_KP_FOUR,
    KS_KP_FIVE,
    KS_KP_SIX,
    KS_KP_PLUS,
    KS_KP_ONE,
    KS_KP_TWO,
    KS_KP_THREE,
    KS_KP_ZERO,
    KS_KP_PERIOD,

    KS_F11 = 0x57,
    KS_F12,

    KS_KP_ENTER = 0x60,
    KS_RCTRL,
    KS_KP_SLASH,
    KS_PRINT_SCREEN,
    KS_RALT,
    KS_BREAK,
    KS_HOME,
    KS_UP,
    KS_PAGE_UP,
    KS_LEFT,
    KS_RIGHT,
    KS_END,
    KS_DOWN,
    KS_PAGE_DOWN,
    KS_INSERT,
    KS_DELETE,

    KS_MAX = 1024,
};

#endif
