
objs-y += scheduler.o
objs-y += signal.o

objs-y += task.o
objs-y += task_fd.o
objs-y += task_sys.o
objs-y += task_api.o
objs-y += task_procfs.o

objs-y += wait_queue.o
objs-y += semaphore.o

objs-y += workqueue.o

