
objs-y += devd.o
objs-y += bdev_name.o
objs-y += cdev_name.o

common-objs-y += arg_parser.o
common-objs-y += alloc_sprintf.o
common-objs-y += columns.o
common-objs-y += db.o
common-objs-y += db_group.o
common-objs-y += strdupx.o

