#!/bin/run_test

# first make a few levels of directories
mkdir /mnt/slave/foo
mkdir /mnt/slave/foo/bar
mkdir /mnt/slave/foo/bar/baz
mkdir /mnt/slave/foo/bar/baz/biz
mkdir /mnt/slave/foo/bar/baz/biz/buzz

# make a very long named directory
mkdir /mnt/slave/foo/bar/baz/biz/buzz/veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongname

# Make 32 levels of directories
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/
mkdir /mnt/slave/foo/bar/baz/biz/buzz/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/

# make a very large number of directories in the same directory
mkdir /mnt/slave/foo/bar/baz1
mkdir /mnt/slave/foo/bar/baz2
mkdir /mnt/slave/foo/bar/baz3
mkdir /mnt/slave/foo/bar/baz4
mkdir /mnt/slave/foo/bar/baz5
mkdir /mnt/slave/foo/bar/baz6
mkdir /mnt/slave/foo/bar/baz7
mkdir /mnt/slave/foo/bar/baz8
mkdir /mnt/slave/foo/bar/baz9
mkdir /mnt/slave/foo/bar/baz10
mkdir /mnt/slave/foo/bar/baz11
mkdir /mnt/slave/foo/bar/baz12
mkdir /mnt/slave/foo/bar/baz13

mkdir /mnt/slave/foo/bar/baz1/biz1
mkdir /mnt/slave/foo/bar/baz1/biz2
mkdir /mnt/slave/foo/bar/baz1/biz3
mkdir /mnt/slave/foo/bar/baz1/biz4
mkdir /mnt/slave/foo/bar/baz1/biz5
mkdir /mnt/slave/foo/bar/baz1/biz6
mkdir /mnt/slave/foo/bar/baz1/biz7
mkdir /mnt/slave/foo/bar/baz1/biz8
mkdir /mnt/slave/foo/bar/baz1/biz9
mkdir /mnt/slave/foo/bar/baz1/biz10
mkdir /mnt/slave/foo/bar/baz1/biz11
mkdir /mnt/slave/foo/bar/baz1/biz12
mkdir /mnt/slave/foo/bar/baz1/biz13
mkdir /mnt/slave/foo/bar/baz1/biz14
mkdir /mnt/slave/foo/bar/baz1/biz15
mkdir /mnt/slave/foo/bar/baz1/biz16
mkdir /mnt/slave/foo/bar/baz1/biz17
mkdir /mnt/slave/foo/bar/baz1/biz18
mkdir /mnt/slave/foo/bar/baz1/biz19
mkdir /mnt/slave/foo/bar/baz1/biz20

mkdir /mnt/slave/foo/bar/baz2/biz1
mkdir /mnt/slave/foo/bar/baz2/biz2
mkdir /mnt/slave/foo/bar/baz2/biz3
mkdir /mnt/slave/foo/bar/baz2/biz4
mkdir /mnt/slave/foo/bar/baz2/biz5
mkdir /mnt/slave/foo/bar/baz2/biz6
mkdir /mnt/slave/foo/bar/baz2/biz7
mkdir /mnt/slave/foo/bar/baz2/biz8
mkdir /mnt/slave/foo/bar/baz2/biz9
mkdir /mnt/slave/foo/bar/baz2/biz10
mkdir /mnt/slave/foo/bar/baz2/biz11
mkdir /mnt/slave/foo/bar/baz2/biz12
mkdir /mnt/slave/foo/bar/baz2/biz13
mkdir /mnt/slave/foo/bar/baz2/biz14
mkdir /mnt/slave/foo/bar/baz2/biz15
mkdir /mnt/slave/foo/bar/baz2/biz16
mkdir /mnt/slave/foo/bar/baz2/biz17
mkdir /mnt/slave/foo/bar/baz2/biz18
mkdir /mnt/slave/foo/bar/baz2/biz19
mkdir /mnt/slave/foo/bar/baz2/biz20
mkdir /mnt/slave/foo/bar/baz2/biz21
mkdir /mnt/slave/foo/bar/baz2/biz22
mkdir /mnt/slave/foo/bar/baz2/biz23
mkdir /mnt/slave/foo/bar/baz2/biz24
mkdir /mnt/slave/foo/bar/baz2/biz25
mkdir /mnt/slave/foo/bar/baz2/biz26
mkdir /mnt/slave/foo/bar/baz2/biz27
mkdir /mnt/slave/foo/bar/baz2/biz28
mkdir /mnt/slave/foo/bar/baz2/biz29
mkdir /mnt/slave/foo/bar/baz2/biz30

mkdir /mnt/slave/foo/bar/baz/foobarfoobar1
mkdir /mnt/slave/foo/bar/baz/foobarfoobar2
mkdir /mnt/slave/foo/bar/baz/foobarfoobar3
mkdir /mnt/slave/foo/bar/baz/foobarfoobar4
mkdir /mnt/slave/foo/bar/baz/foobarfoobar5
mkdir /mnt/slave/foo/bar/baz/foobarfoobar6
mkdir /mnt/slave/foo/bar/baz/foobarfoobar7
mkdir /mnt/slave/foo/bar/baz/foobarfoobar8
mkdir /mnt/slave/foo/bar/baz/foobarfoobar9
mkdir /mnt/slave/foo/bar/baz/foobarfoobar10
mkdir /mnt/slave/foo/bar/baz/foobarfoobar11
mkdir /mnt/slave/foo/bar/baz/foobarfoobar12
mkdir /mnt/slave/foo/bar/baz/foobarfoobar13
mkdir /mnt/slave/foo/bar/baz/foobarfoobar14
mkdir /mnt/slave/foo/bar/baz/foobarfoobar15
mkdir /mnt/slave/foo/bar/baz/foobarfoobar16
mkdir /mnt/slave/foo/bar/baz/foobarfoobar17
mkdir /mnt/slave/foo/bar/baz/foobarfoobar18
mkdir /mnt/slave/foo/bar/baz/foobarfoobar19
mkdir /mnt/slave/foo/bar/baz/foobarfoobar20
mkdir /mnt/slave/foo/bar/baz/foobarfoobar21
mkdir /mnt/slave/foo/bar/baz/foobarfoobar22
mkdir /mnt/slave/foo/bar/baz/foobarfoobar23
mkdir /mnt/slave/foo/bar/baz/foobarfoobar24
mkdir /mnt/slave/foo/bar/baz/foobarfoobar25
mkdir /mnt/slave/foo/bar/baz/foobarfoobar26
mkdir /mnt/slave/foo/bar/baz/foobarfoobar27
mkdir /mnt/slave/foo/bar/baz/foobarfoobar28
mkdir /mnt/slave/foo/bar/baz/foobarfoobar29
mkdir /mnt/slave/foo/bar/baz/foobarfoobar30
mkdir /mnt/slave/foo/bar/baz/foobarfoobar31
mkdir /mnt/slave/foo/bar/baz/foobarfoobar32
mkdir /mnt/slave/foo/bar/baz/foobarfoobar33
mkdir /mnt/slave/foo/bar/baz/foobarfoobar34
mkdir /mnt/slave/foo/bar/baz/foobarfoobar35
mkdir /mnt/slave/foo/bar/baz/foobarfoobar36
mkdir /mnt/slave/foo/bar/baz/foobarfoobar37
mkdir /mnt/slave/foo/bar/baz/foobarfoobar38
mkdir /mnt/slave/foo/bar/baz/foobarfoobar39
mkdir /mnt/slave/foo/bar/baz/foobarfoobar40

mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar1
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar2
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar3
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar4
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar5
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar6
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar7
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar8
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar9
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar10
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar11
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar12
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar13
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar14
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar15
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar16
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar17
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar18
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar19
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar20
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar21
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar22
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar23
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar24
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar25
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar26
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar27
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar28
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar29
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar30
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar31
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar32
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar33
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar34
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar35
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar36
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar37
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar38
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar39
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar40
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar41
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar42
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar43
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar44
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar45
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar46
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar47
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar48
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar49
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar50
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar51
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar52
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar53
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar54
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar55
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar56
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar57
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar58
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar59
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar60
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar61
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar62
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar63
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar64
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar65
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar66
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar67
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar68
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar69
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar70
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar71
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar72
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar73
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar74
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar75
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar76
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar77
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar78
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar79
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar80
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar81
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar82
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar83
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar84
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar85
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar86
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar87
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar88
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar89
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar90
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar91
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar92
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar93
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar94
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar95
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar96
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar97
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar98
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar99
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar100
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar101
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar102
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar103
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar104
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar105
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar106
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar107
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar108
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar109
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar110
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar111
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar112
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar113
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar114
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar115
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar116
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar117
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar118
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar119
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar120
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar121
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar122
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar123
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar124
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar125
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar126
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar127
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar128
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar129
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar130
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar131
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar132
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar133
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar134
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar135
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar136
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar137
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar138
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar139
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar140
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar141
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar142
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar143
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar144
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar145
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar146
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar147
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar148
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar149
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar150
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar151
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar152
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar153
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar154
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar155
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar156
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar157
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar158
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar159
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar160
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar161
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar162
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar163
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar164
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar165
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar166
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar167
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar168
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar169
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar170
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar171
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar172
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar173
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar174
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar175
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar176
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar177
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar178
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar179
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar180
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar181
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar182
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar183
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar184
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar185
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar186
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar187
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar188
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar189
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar190
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar191
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar192
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar193
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar194
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar195
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar196
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar197
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar198
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar199
mkdir /mnt/slave/foo/bar/baz4/foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar200
