#!/bin/perl -w
use strict;
use warnings;

sub print_cpp {
    my ($id, $val) = @_;

    if ($val eq 'y') {
        print "#define $id\n";
    } elsif ($val eq 'n') {
        print "/* #define $id */\n";
    } else {
        print "#define $id $val\n";
    }
}

sub print_make {
    my ($id, $val) = @_;

    print "$id := $val\n";
}

my $genopt = 0;

if ($ARGV[0] eq "make") {
    $genopt = 1;
} elsif ($ARGV[0] eq "cpp") {
    $genopt = 2;
}

if ($genopt == 2) {
    print "/*\n";
    print " * Configuration file generated by $0\n";
    print " */\n";
    print "#ifndef INCLUDE_CONFIG_AUTOCONF_H\n";
    print "#define INCLUDE_CONFIG_AUTOCONF_H\n";
}

foreach my $line (<STDIN>) {
    chomp($line);
    if ($line =~ /^\s*$/) {
        next;
    }
    if (!(substr($line, 0, 1) eq '#')) {
        my @str = split(' ', $line);
        my $id  = $str[0];
        my $val = $str[2];
        
        if ($genopt == 1) {
            print_make($id, $val);
        } else {
            print_cpp($id, $val);
        }
    }
}

if ($genopt == 2) {
    print "#endif\n";
}

