
objs-$(CONFIG_CONSOLE_DRIVER) += console.o
objs-$(CONFIG_CONSOLE_DRIVER) += screen.o
objs-$(CONFIG_CONSOLE_DRIVER) += keyboard.o

objs-$(CONFIG_TTY_DRIVER) += tty.o
objs-$(CONFIG_TTY_DRIVER) += tty_termios.o

objs-y += mem.o
objs-y += mem_zero.o
objs-y += mem_full.o
objs-y += mem_null.o

subdir-y += serial

