
objs-y += inode.o
objs-y += block.o
objs-y += block_dev.o
objs-y += bdflush.o
objs-y += char_dev.o
objs-y += file_system.o
objs-y += inode_table.o
objs-y += sync.o

objs-y += file.o
objs-y += dir.o
objs-y += fs.o
objs-y += namei.o
objs-y += vfs.o
objs-y += sys.o
objs-y += pipe.o
objs-y += poll.o
objs-y += access.o

objs-y += exec.o
objs-y += params.o
objs-y += binfmt_table.o
objs-y += binfmt_elf.o
objs-y += binfmt_script.o

objs-y += seq_file.o

subdir-$(CONFIG_FS_EXT2_DRIVER) += ext2
subdir-$(CONFIG_FS_PROCFS_DRIVER) += procfs

