
objs-y += inode.o
objs-y += block.o
objs-y += block_dev.o
objs-y += char_dev.o
objs-y += file_system.o
objs-y += inode_table.o
objs-y += sync.o

objs-y += file.o
objs-y += fs.o
objs-y += namei.o
objs-y += vfs.o
objs-y += sys.o

objs-y += exec.o
objs-y += binfmt_table.o
objs-y += binfmt_elf.o

subdir-y += ext2

