
objs-y += ip.o
objs-y += ip_route.o

objs-y += icmp.o
objs-y += udp.o

objs-y += tcp.o
objs-y += tcp_data.o
objs-y += tcp_input.o
objs-y += tcp_output.o
objs-y += tcp_timer.o
objs-y += tcp_test.o

objs-y += ip_raw.o
objs-y += ip_socket_lookup.o
